### ISSUE TITLE
Frontpage example has error?

### ISSUE THREAD

**Issue by cefn** [vidigami/backbone-mongo#16]
I'm new to this area so it might be a spurious claim. However, it sure looks like the line in your first frontpage javascript example which reads...

```
Task.prototype.sync = require('backbone-orm').sync(Change);
```

...should actually read...

```
Change.prototype.sync = require('backbone-orm').sync(Change);
```

**Comment by kmalakoff** [comment]
Yup, that's a copy-paste bug. I'll fix it.

Thank you!
